# Practical session 3 - Practice with numpy

Course: [SDIA-Python](https://github.com/guilgautier/sdia-python)

Date: 10/06/2021

Instructor: [Guillaume Gautier](https://guilgautier.github.io/)

Students (pair):
- [Student 1]([link](https://github.com/username1))
- [Student 2]([link](https://github.com/username2))

In [47]:
%load_ext autoreload
%autoreload 2

import numpy as np
from lab2.utils import get_random_number_generator

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
my_array = np.array([0])
print(type(my_array))
dir(np.ndarray)

<class 'numpy.ndarray'>


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Propose at leat 2 ways to create an integer vector of size 100 made of 1s

In [7]:
one = np.ones(100)
one_bis = np.zeros(100) + 1
print(one,"\n", one_bis)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


Create a vector with values ranging from 10 to 49

In [9]:
arange = np.arange(10,50)
print(arange)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Propose a way to construct the vector $(0.0, 0.2, 0.4, 0.6, 0.8)$

In [11]:
arange_bis = np.arange(0.0,1.0,0.2)
print(arange_bis)

[0.  0.2 0.4 0.6 0.8]


Convert a float array into an integer array in place

In [12]:
arange_bis.astype(int)

array([0, 0, 0, 0, 0])

Given a boolean array

- return the indices where 
- negate the array inplace? 

In [24]:
boolean = np.array([False,False,False,True,False,True])
np.argwhere(boolean)
np.invert(boolean, out = boolean)

array([ True,  True,  True, False,  True, False])

Given 2 vectors $u, v$, propose at least

- 2 ways to compute the inner product $v^{\top} u$ (here they must have the same size)
- 2 ways to compute the outer product matrix $u v^{\top}$
- 2 ways to compute the outer sum matrix "$M = u + v^{\top}$", where $M_{ij} = u_i + v_j$

In [29]:
u,v = np.arange(1,10),np.arange(11,20)
np.inner(v,u)
np.dot(v,u)

735

In [33]:
np.outer(u,v)
np.multiply.outer(u,v)


array([[ 11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 33,  36,  39,  42,  45,  48,  51,  54,  57],
       [ 44,  48,  52,  56,  60,  64,  68,  72,  76],
       [ 55,  60,  65,  70,  75,  80,  85,  90,  95],
       [ 66,  72,  78,  84,  90,  96, 102, 108, 114],
       [ 77,  84,  91,  98, 105, 112, 119, 126, 133],
       [ 88,  96, 104, 112, 120, 128, 136, 144, 152],
       [ 99, 108, 117, 126, 135, 144, 153, 162, 171]])

In [32]:
np.add.outer(u,v)


array([[12, 13, 14, 15, 16, 17, 18, 19, 20],
       [13, 14, 15, 16, 17, 18, 19, 20, 21],
       [14, 15, 16, 17, 18, 19, 20, 21, 22],
       [15, 16, 17, 18, 19, 20, 21, 22, 23],
       [16, 17, 18, 19, 20, 21, 22, 23, 24],
       [17, 18, 19, 20, 21, 22, 23, 24, 25],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [20, 21, 22, 23, 24, 25, 26, 27, 28]])

Given the following matrix

$$
M = 
\begin{pmatrix}
    0 & 1 & 2 \\
    3 & 4 & 5 \\
    6 & 7 & 8 \\
\end{pmatrix}
$$

- Create $M$ using as a list of lists and access the element in the middle
- Propose at least 2 ways to create $M$ using numpy and access the element in the middle
- Swap its first and second row
- Propose at least 3 ways to extract the submatrix $\begin{pmatrix}4 & 5 \\7 & 8 \\\end{pmatrix}$
- Propose at least 2 ways to extract the diagonal of $M$
- Propose at least 2 ways to compute $M^3$
- Compute $v^{\top} M$, resp. $M N$ for a vector, resp. a matrix of your choice. 
- Propose 2 ways to "vectorize" the matrix, i.e., transform it into
  - $(0, 1, 2, 3, 4, 5, 6, 7, 8)$
  - $(0, 3, 6, 1, 4, 7, 2, 5, 8)$
- Consider $v = (1, 2 , 3)$, compute the
  - row-wise multiplication of $M$ by $v$ ($M_{i\cdot}$ is multiplied by $v_i$)
  - column-wise multiplication of $M$ by $v$ ($M_{\cdot j}$ is multiplied by $v_i$)

Write a function `is_symmetric` that checks whether a given n x n matrix is symmetric, and provide an example

In [48]:
M = [[0, 1, 2],[3,4,5],[6,7,8]]
print(M,"\n",M[1][1])

M = np.array(M)
M = np.arange(9).reshape(3,3)
print("\n",M, "\n", M[1,1])

M[[0, 1]] = M[[1, 0]]
print("\n",M)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]] 
 4

 [[0 1 2]
 [3 4 5]
 [6 7 8]] 
 4

 [[3 4 5]
 [0 1 2]
 [6 7 8]]


In [52]:
M = np.arange(9).reshape(3,3)
M[1:3,1:3]
I = slice(1,3)
print(M[I,I])

np.where()



[[4 5]
 [7 8]]


## Random

REQUIREMENT: USE THE FUNCTION `get_random_number_generator` as previously used in Lab 2.

Consider the Bernoulli(0.4) distribution

- Propose at least 2 ways to generate n=1000 samples from it
- Compute the empirical mean and variance

Consider a random matrix of size $50 \times 100$, filled with i.i.d. standard Gaussian variables, compute

- the absolute value of each entry
- the sum of each row
- the sum of each colomn 
- the (euclidean) norm of each row
- the (euclidean) norm of each column