# Practical session 3 - Practice with numpy

Course: [SDIA-Python](https://github.com/guilgautier/sdia-python)

Date: 10/06/2021

Instructor: [Guillaume Gautier](https://guilgautier.github.io/)

Students (pair):
- [Student 1]([link](https://github.com/username1))
- [Student 2]([link](https://github.com/username2))

In [2]:
%load_ext autoreload
%autoreload 2

import numpy as np
from sdia_python.lab2.utils import get_random_number_generator

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
my_array = np.array([0])
print(type(my_array))
dir(np.ndarray)

<class 'numpy.ndarray'>


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Propose at leat 2 ways to create an integer vector of size 100 made of 1s

In [7]:
v1 = np.ones(100)
v2 = np.zeros(100) + 1


Create a vector with values ranging from 10 to 49

In [8]:
v = np.arange(10, 50, 1)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Propose a way to construct the vector $(0.0, 0.2, 0.4, 0.6, 0.8)$

In [11]:
v = np.linspace(0, 0.8, 5)
print(v)

[0.  0.2 0.4 0.6 0.8]


Convert a float array into an integer array in place

In [19]:

v = np.arange(0, 50, 1, dtype=float);
v.astype(int)
print(v)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


Given a boolean array

- return the indices where 
- negate the array inplace? 

In [61]:
v_bool = np.array([True, False, True, True, True, False, False, True])
print(np.where(v_bool))
print(np.argwhere(v_bool))
v_neg = ~v_bool
print(v_neg)
print((1 - v_bool).astype(bool))


(array([0, 2, 3, 4, 7]),)
[[0]
 [2]
 [3]
 [4]
 [7]]
[False  True False False False  True  True False]
[False  True False False False  True  True False]


Given 2 vectors $u, v$, propose at least

- 2 ways to compute the inner product $v^{\top} u$ (here they must have the same size)
- 2 ways to compute the outer product matrix $u v^{\top}$
- 2 ways to compute the outer sum matrix "$M = u + v^{\top}$", where $M_{ij} = u_i + v_j$

In [95]:
u = np.random.randn(20)
v = np.random.randn(20)

p1 = v.T @ u 
p2 = np.inner(v, u)


p3 = np.outer(u, v)
p4 = np.multiply.outer(u, v)


M = np.add.outer(u, v)
M = u.reshape((20, 1)) + v.reshape((20, 1)).T


10.618299231724116
10.618299231724116
(20, 20)
(20, 20)
[-1.54119763  1.35069458 -1.62260443 -1.47210401  0.20441304  0.20480766
  0.84258079 -1.11509423  0.15849686  0.36703436 -1.05588646 -0.55234638
  2.26867257  0.21371633  0.84252551  0.06047514  0.10491212  0.15667078
  0.98926983  2.00058421]
[-1.54119763  1.35069458 -1.62260443 -1.47210401  0.20441304  0.20480766
  0.84258079 -1.11509423  0.15849686  0.36703436 -1.05588646 -0.55234638
  2.26867257  0.21371633  0.84252551  0.06047514  0.10491212  0.15667078
  0.98926983  2.00058421]


Given the following matrix

$$
M = 
\begin{pmatrix}
    0 & 1 & 2 \\
    3 & 4 & 5 \\
    6 & 7 & 8 \\
\end{pmatrix}
$$

- Create $M$ using as a list of lists and access the element in the middle
- Propose at least 2 ways to create $M$ using numpy and access the element in the middle
- Swap its first and second row
- Propose at least 3 ways to extract the submatrix $\begin{pmatrix}4 & 5 \\7 & 8 \\\end{pmatrix}$
- Propose at least 2 ways to extract the diagonal of $M$
- Propose at least 2 ways to compute $M^3$
- Compute $v^{\top} M$, resp. $M N$ for a vector, resp. a matrix of your choice. 
- Propose 2 ways to "vectorize" the matrix, i.e., transform it into
  - $(0, 1, 2, 3, 4, 5, 6, 7, 8)$
  - $(0, 3, 6, 1, 4, 7, 2, 5, 8)$
- Consider $v = (1, 2 , 3)$, compute the
  - row-wise multiplication of $M$ by $v$ ($M_{i\cdot}$ is multiplied by $v_i$)
  - column-wise multiplication of $M$ by $v$ ($M_{\cdot j}$ is multiplied by $v_i$)

Write a function `is_symmetric` that checks whether a given n x n matrix is symmetric, and provide an example

In [68]:
M = [[3*i+j for j in range(3)] for i in range(3)]
print(M[1][1])

4


In [82]:
M = np.array(M)
M = np.arange(0,9, 1).reshape(3, 3)
print(M[1,1])

4


In [83]:
a = 2
b = 3
a, b = b, a
print(a, b)
M[[0, 1]] = M[[1, 0]]
print(M)

3 2
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [99]:
M = np.arange(0, 9, 1).reshape(3, 3)
print(M)
print(M[1:, 1:])
print(M[-2:, -2:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[4 5]
 [7 8]]
[[4 5]
 [7 8]]


In [100]:
d = np.diag(M)
print(d)
print(np.array([M[i,i] for i in range(len(M))]))

[0 4 8]
[0 4 8]


In [101]:
print((M @ M @ M).shape)
print(np.power(M, 3).shape)

(3, 3)
(3, 3)


In [102]:
v = np.random.randn(3,1)
print(v.T @ M)


[[3.7047487  3.33669614 2.96864359]]


In [105]:
print(M)
print(M.flatten())
print(M.reshape(9))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [109]:
v = np.array([1, 2, 3])
print(v.reshape(3, 1) * M)
print(v * M)

[[ 0  1  2]
 [ 6  8 10]
 [18 21 24]]
[[ 0  2  6]
 [ 3  8 15]
 [ 6 14 24]]


In [115]:
def is_symetric(M):
    return np.all(M == M.T)


M = np.diag([3,4,45,6])
print(M)
print(is_symetric(M))

[[ 3  0  0  0]
 [ 0  4  0  0]
 [ 0  0 45  0]
 [ 0  0  0  6]]
True


## Random

REQUIREMENT: USE THE FUNCTION `get_random_number_generator` as previously used in Lab 2.

Consider the Bernoulli(0.4) distribution

- Propose at least 2 ways to generate n=1000 samples from it
- Compute the empirical mean and variance

Consider a random matrix of size $50 \times 100$, filled with i.i.d. standard Gaussian variables, compute

- the absolute value of each entry
- the sum of each row
- the sum of each colomn 
- the (euclidean) norm of each row
- the (euclidean) norm of each column